---
# tasks file for ansible-role-libre-speedtest

- name: "Include tasks from lookup playbook"
  include_tasks: lookup.yaml

- name: "Include tasks from prerequisites playbook"
  include_tasks: prerequisites.yaml

- name: "Include tasks from install playbook"
  include_tasks: install.yaml
  when:
    - install is defined
    - install | bool

- name: "Include tasks from speedtest playbook"
  include_tasks: speedtest.yaml

- name: "Show Speedtest results"
  debug:
    msg:
      - "Download: {{ download_mbps }} Mbps"
      - "Upload: {{ upload_mbps }} Mbps"
